export const COINS_LOADING='COINS_LOADING';
export const COINS_SUCCESS='COINS_SUCCESS';
export const COINS_ERROR='COINS_ERROR';


export const SEARCHED_VALUE = 'SEARCHED_VALUE';

export const CURRENT_PAGE = 'CURRENT_PAGE';

export const COINS_PAGE_LOADING='COINS_PAGE_LOADING';
export const COINS_PAGE_SUCCESS='COINS_PAGE_SUCCESS';
export const COINS_PAGE_SUCCESS_CRYPTO1='COINS_PAGE_SUCCESS_CRYPTO1';
export const COINS_PAGE_SUCCESS_CRYPTO2='COINS_PAGE_SUCCESS_CRYPTO2';
export const COINS_PAGE_ERROR='COINS_PAGE_ERROR';

export const COINS_MARKET_LOADING='COINS_MARKET_LOADING';
export const COINS_MARKET_SUCCESS='COINS_MARKET_SUCCESS';
export const COINS_MARKET_SUCCESS_CRYPTO1='COINS_MARKET_SUCCESS_CRYPTO1';
export const COINS_MARKET_SUCCESS_CRYPTO2='COINS_MARKET_SUCCESS_CRYPTO2';
export const COINS_MARKET_ERROR='COINS_MARKET_ERROR';

export const DAYS = 'DAYS';

export const BUTTON_TOGGLE = 'BUTTON_TOGGLE';

export const CRYPTO1 = 'CRYPTO1';
export const CRYPTO2 = 'CRYPTO2';


export const WATCHLIST = 'WATCHLIST';